kind: Pod
apiVersion: v1
metadata:
   name: env
spec:
  containers:
  - name: nginx
    image: nginx
    environment:
    - name: course
      value: Devops
    - name: trainer
      value: "siva reddy"
    - name: duration
      value: "120hours"