apiVersion: apps/v1
kind: Replicaset
metadata:
  name: nginx
  # the labels are replica set 
  labels:
    app: frontend
    tier: web
  spec:
  replicas: 3
  selector:
   # replica use the labels to find the pods for creating desride number of replica
    matchLabels:
    app: frontend
    tier: web
  #pod templte
    template:
      metadata:
        labels:
        app: frontend
        tier: web
      spec:
        containers:
        - name: nginx
          image: nginx