apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
     # soft limit
     requests:
       memory: "68mi"
       cpu: "100m"
       # hard limit
       limits:
         memory: "128mi"
         cpu: "150m"